### ISSUE TITLE
Battery percentage stuck on 52%

### ISSUE THREAD

**Issue by JoeyNRG** [knulli-cfw/distribution#126] opened 2024-09-22 19:27 UTC
### Knulli build version

40-dev-d3b520f949 2024/07/21

### Your architecture

RG35XXH

### Issue description

Battery percentage gets stuck on emulation station front end. 

### Detailed reproduction steps

Leaving the device sitting whilst not playing a game eventually sticks the battery percentage. Then after loading a game and coming back to the front end it still reports the same percentage. But loading a game and dropping to RA shows correct percentage. 

### Details of any attempts to fix this yourself

I have tried to load a game and come out, refreshing game list but only restarting the device fixes the battery percentage.

### Details of any modifications you have made to Knulli.

I haven't modified the os

**Comment by fedekrum** [comment] 2024-10-06 23:39
I have seen this too. Not always on 52%, but for example sometimes I read 82% on screen and after a restart is 100%

**Comment by Mikhailzrick** [comment] 2024-11-07 09:48
It happens sometimes. The issue is with ES. We recently forked ES, so we may be able to nail down the issue in the near future. It may actually already be fixed as I’ve not seen it from my own testing in quite a while.

**Comment by bremedios** [comment] 2024-11-18 21:18
I can confirm that this still happens on a RG40XXV running V41-dev-a1102db1e2 2024/11/07.

A repro case for this is as follows (not sure if all steps are required)

1. Plug power cable
2. Start game (I ran a GBA game)
3. Unplug power cable
4. Press power button to enter suspend/sleep
5. Plug in power cable

The system is still properly reporting capacity and charge level (sys/class) but its not updating in ES.

batocera-info is also showing the correct Battery %.

**Comment by bremedios** [comment] 2024-11-19 21:59
The root cause of this issue is that when launching something that uses SDL, the tick count gets reset so the check threads do not run until the tick count counts over until it gets back to the same value.

A pull request for this will be incoming.

**Comment by bremedios** [comment] 2024-12-06 18:34
The fix for this should be in the firefly release.

**Closed as completed** 2024-12-07 00:18 UTC
