### ISSUE TITLE
Retroachivements option in Settings not works

### ISSUE THREAD

**Issue by symbuzzer** [knulli-cfw/distribution#39] opened 2024-06-05 03:02 UTC
### Knulli build version

20240530 

### Your architecture

RG35XX PLUS

### Issue description

Retroachivements login works. Also it works in games without any problem. But when I wanted to see my achivements from Settings menu, it gives error every time.

### Detailed reproduction steps

- Login Retroachivements
- Try to run Retroachivements from Settings

### Details of any attempts to fix this yourself

Removed my Retroachivements account and re-enter again.
Made a clean install.

### Details of any modifications you have made to Knulli.

-

**Comment by arcangel2p** [comment] 2024-06-05 09:00
I can confirm it also happens to me.
Tried reflashing the whole system and the error persists.

The error it gives when trying to access the Retroachievements portion on the Emulestation menu is like:

`"message "Unauthenticated""errors":[{"status":419,"code":"unauthorized","title"":"Unauthenticated.:"`

**Comment by symbuzzer** [comment] 2024-06-05 11:06
> I can confirm it also happens to me. Tried reflashing the whole system and the error persists.
> 
> The error it gives when trying to access the Retroachievements portion on the Emulestation menu is like:
> 
> `"message "Unauthenticated""errors":[{"status":419,"code":"unauthorized","title"":"Unauthenticated.:"`

Same error

**Comment by Louisvh** [comment] 2024-06-09 17:02
I don't think the system ever passes an API key when [constructing the API url](https://github.com/batocera-linux/batocera-emulationstation/blob/808eefe7f92b1bffb03adb76491916577dcebb01/es-app/src/RetroAchievements.cpp#L302C2-L302C124). I indeed see the same error when I try to request 

https://retroachievements.org/API/API_GetUserSummary.php?u=[my_username]

but not when I request

https://retroachievements.org/API/API_GetUserSummary.php?u=[my_username]&y=[my_api_key]

**Comment by Dreadlocke12** [comment] 2024-06-12 17:15
Can confirm the issue is the same for me on a rg35xx h. Achievements however seems to work though.

**Comment by dAtA-TRoN** [comment] 2024-06-17 17:33
Yep, same here 🙋🏻‍♂️.

**Comment by Zxquad** [comment] 2024-07-06 22:07
Yes same here on H and also Plus version.

**Comment by HoroTW** [comment] 2024-07-22 16:08
For those who haven't found it yet, the developers are aware of it. (see links below)

[Q&A Link](https://github.com/knulli-cfw/knulli.org/blob/d50704a4b267cd6b00dd5decfaa064e7b403dbe8/docs/faq/troubleshooting.md?plain=1#L61)

[retro-achievements.md](https://github.com/knulli-cfw/knulli.org/blob/d50704a4b267cd6b00dd5decfaa064e7b403dbe8/docs/play/retro-achievements.md?plain=1#L5)

**Comment by bladeoner** [comment] 2024-07-23 16:15
This is fixed in a later version of EmulationStation, I have opened a PR for that.

**Closed as completed** 2024-07-24 15:48 UTC

**Comment by symbuzzer** [comment] 2024-08-25 10:44
@bladeoner @acmeplus Are you sure this PR fixed it? I compiled latest knull-main and it seems still has this issue

**Comment by bladeoner** [comment] 2024-08-25 10:57
Hi @symbuzzer I am sure it is working, did you make a copy of the [**keys.txt.sample**](https://github.com/knulli-cfw/distribution/blob/knulli-main/package/batocera/emulationstation/batocera-emulationstation/keys.txt.sample) file called it **keys.txt**, and filled in your Retroachievement, username and API key?

That is required to get it to work.

**Comment by symbuzzer** [comment] 2024-08-25 16:04
> Hi @symbuzzer I am sure it is working, did you make a copy of the [**keys.txt.sample**](https://github.com/knulli-cfw/distribution/blob/knulli-main/package/batocera/emulationstation/batocera-emulationstation/keys.txt.sample) file called it **keys.txt**, and filled in your Retroachievement, username and API key?
> 
> That is required to get it to work.

No, I didnt know. Is it working on 07/21 public too?

**Comment by bladeoner** [comment] 2024-08-28 06:33
> > Hi @symbuzzer I am sure it is working, did you make a copy of the [**keys.txt.sample**](https://github.com/knulli-cfw/distribution/blob/knulli-main/package/batocera/emulationstation/batocera-emulationstation/keys.txt.sample) file called it **keys.txt**, and filled in your Retroachievement, username and API key?
> > That is required to get it to work.
> 
> No, I didnt know. Is it working on 07/21 public too?

Hi, it won't work in the 07/21 public, but in the next release.

**Comment by symbuzzer** [comment] 2024-08-30 18:17
> Hi @symbuzzer I am sure it is working, did you make a copy of the [**keys.txt.sample**](https://github.com/knulli-cfw/distribution/blob/knulli-main/package/batocera/emulationstation/batocera-emulationstation/keys.txt.sample) file called it **keys.txt**, and filled in your Retroachievement, username and API key?
> 
> That is required to get it to work.

Can u share an example of this file? It seems sample file has no input for RA. Also where do I copy this file?

**Comment by bladeoner** [comment] 2024-09-06 09:25
Hi @symbuzzer, you can find the **keys.txt.sample** in the repository:

https://github.com/knulli-cfw/distribution/blob/knulli-main/package/batocera/emulationstation/batocera-emulationstation/keys.txt.sample

You need to make a copy of **keys.txt.sample**, put it in the same directory and name it **keys.txt**

Example **keys.txt**:
```
SCREENSCRAPER_DEV_LOGIN=devid=DEVID&devpassword=DEVPASSWORD
GAMESDB_APIKEY=APIKEY
CHEEVOS_DEV_LOGIN=z=RETROACHIEVEMENTSUSERNAME&y=APIKEYID
HFS_DEV_LOGIN==
```

**Comment by symbuzzer** [comment] 2024-09-06 10:04
@bladeoner on device, where should I create this file sir?

**Comment by bladeoner** [comment] 2024-09-06 10:07
package/batocera/emulationstation/batocera-emulationstation/keys.txt

**Comment by symbuzzer** [comment] 2024-09-06 16:49
> package/batocera/emulationstation/batocera-emulationstation/keys.txt

this path doesnt exist on device

**Comment by bladeoner** [comment] 2024-09-09 05:55
Path: package/batocera/emulationstation/batocera-emulationstation
File: keys.txt
