### ISSUE TITLE
knulli battery drain rg35xxh 

### ISSUE THREAD

**Issue by manuel09** [knulli-cfw/distribution#94] opened 2024-07-28 14:14 UTC
### Knulli build version

knulli-h700-rg35xx-h-40-20240721

### Your architecture

RG35XXH 

### Issue description

when the console is in stand by the battery drops quickly

### Detailed reproduction steps

I installed Knulli on the SD with Rufus, I inserted the SD into my rg35xxh, when you leave the console on without doing anything the battery goes down very quickly

### Details of any modifications you have made to Knulli.

I have not installed third party packages

**Comment by HoroTW** [comment] 2024-07-30 16:58
You mean like with emu station running and the screen turned on?
Can you try to quantify "very quickly"?

~Horo

**Comment by HoroTW** [comment] 2024-07-30 18:23
As a reference on my RG35XXH, I turned the screen brightness and volume down to 0%, I **didn't** turn off WiFi, then let the system sit there for an hour, after which the device lost 9%, which I would guess is kind of normal.
Does yours lose much more under the same circumstances?

**Comment by manuel09** [comment] 2024-07-30 21:00
yes, the battery really loses a lot even when I restart the console.

**Comment by HoroTW** [comment] 2024-07-31 22:44
Hmm, I'm really not sure why this could happen, maybe the battery algorithm needs to be calibrated (that's a wild guess, I don't know what the algorithm does, but Knulli got a new one with this release).

Did you charge it to 100% and let it discharge to near 0 (<10%)?
Any change after that?

Or another question would be, if the device just does nothing, does it get very hot? If it is not just a battery reading issue, you would see the device getting really hot (not just slightly warm in the middle (slightly up and left) of the screen (where the CPU sits)).

**Comment by DomiKamu** [comment] 2024-08-12 10:16
Hello, I'm new RG40XX H user, using **KNULLI** (**20240721**, lastest release in date), also I've noticed the battery is losing a lot, from EmulationStation (console selection, no sound only static console image). Either the WiFi is enabled or disabled. RGB around sticks are turned off (RGB isn't supported by KNULLI/ES at the moment). Two installed TF cards (both SanDisk Extreme PRO 64 GB as #1, plus 256 GB extFAT as #2 for games/medias...).

I've tried to charge the battery to full 100%, then a full discharge (below 5%), the full charge again, but nothing change. Battery drain seems to be important (in my opinion). From 100% to 5% is around 3 hours.

Regards.

**Comment by HoroTW** [comment] 2024-08-14 18:20
That ... sounds really bad, (considering I can play actual games with the screen on ~50% brightness for more than 3 hours), can you answer if the device gets hot while it is just lying and discharging? also what is/was your screen brightness for this?

**Comment by Mikhailzrick** [comment] 2024-11-07 09:02
There’s a lot of variables involved. Brightness, sound volume, if you have powermode set to high performance, what games you are playing. Etc. If the system is at the max 1.5Ghz clock speed with 100% brightness and volume with wifi and bluetooth both enabled 3-4 hours does not sound unreasonable.

when suspended, expect roughly 4% per hour drain. So that’s around 25 hours.

closing as this doesn’t sound like a bug but expected behavior.

**Closed as completed by Mikhailzrick** 2024-11-07 09:02 UTC
